server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  include mime.types; # Adicionando suporte a tipos MIME
  default_type application/octet-stream; # Tipo padrão para arquivos desconhecidos

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(js|css|png|jpg|jpeg|svg|ico|woff2?)$ {
    expires 30d;
    add_header Cache-Control "public";
  }
}
